name: Lint & Test

on:
  pull_request:
    branches:
      - "*"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Install modules
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Restore node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Run ESLint
        run: npm run lint
